{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autopilot.dbSecretName" . }}
  labels:
    {{- include "autopilot.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ include "autopilot.fullname" . }}
  password: {{ randAlphaNum 16 }}
{{- end }}