apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-adk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google-adk
  template:
    metadata:
      labels:
        app: google-adk
    spec:
      serviceAccount: google-adk-sa
      containers:
      - name: google-adk
        imagePullPolicy: Always
        image: redi21/google-adk:dev
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
          requests:
            memory: "2Gi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: GOOGLE_CLOUD_PROJECT
            value: krateo-autopilot
          - name: GOOGLE_CLOUD_LOCATION
            value: europe-west8
          - name: GOOGLE_GENAI_USE_VERTEXAI
            value: "true"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/application_default_credentials.json
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token
                key: token
        volumeMounts:
          - name: gcloud-credentials
            mountPath: /var/secrets/google
            readOnly: true
      volumes:
        - name: gcloud-credentials
          secret:
            secretName: gcloud-credentials

# kubectl create secret generic github-token --from-literal=token=<your_token> -n krateo-system
# kubectl create secret generic github-token --from-literal=token=<your_token>