apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gemini-flash
  namespace: krateo-system
spec:
  model: gemini-2.5-flash
  provider: Gemini
  apiKeySecret: gemini-api-key
  apiKeySecretKey: apiKey
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gemini-pro
  namespace: krateo-system
spec:
  model: gemini-2.5-pro
  provider: Gemini
  apiKeySecret: gemini-api-key
  apiKeySecretKey: apiKey
