apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: krateo-restaction-agent
  namespace: krateo-system
spec:
  type: Declarative
  description: "Generates valid Krateo RESTAction CRDs for making declarative REST API calls"
  declarative:
    deployment:
      env:
        - name: GOOGLE_GENAI_USE_VERTEXAI
          value: "0"
    modelConfig: gemini-flash
    stream: true
    promptTemplate:
      dataSources:
        - kind: ConfigMap
          name: krateo-prompts-eng
          alias: prompts
    systemMessage: |
      {{include "prompts/restaction_agent"}}
